export const menuItems = [
  {
    id: "Hair",
    label: "Hair",
    children: [
      { id: "Shampoos", label: "Shampoos" },
      { id: "Hair rinse", label: "Hair rinse" },
      { id: "Hair balm", label: "Hair balm" },
      { id: "Conditioner", label: "Conditioner" },
      { id: "Hair masks", label: "Hair masks" },
      { id: "Scalp treatments", label: "Scalp treatments" },
      { id: "Anti-dandruff", label: "Anti-dandruff" },
      { id: "Hair lotion", label: "Hair lotion" },
      { id: "Hair oil", label: "Hair oil" },
      { id: "Hair serum", label: "Hair serum" },
      { id: "Hair cream", label: "Hair cream" },
      { id: "Hair spray", label: "Hair spray" },
      { id: "Hair keratin", label: "Hair keratin" },
    ],
  },
  {
    id: "Perfume",
    label: "Perfume",
    children: [
      { id: "Women's Perfume", label: "Women's Perfume" },
      { id: "Men's Perfume", label: "Men's Perfume" },
      { id: "Unisex Perfume", label: "Unisex Perfume" },
      { id: "Children's Perfume", label: "Children's Perfume" },
      { id: "Wonder Bundle", label: "Wonder Bundle" },
      { id: "Sets", label: "Sets" },
      { id: "Miniatures", label: "Miniatures" },
      { id: "Eau de Parfum", label: "Eau de Parfum" },
      { id: "Eau de Toilette", label: "Eau de Toilette" },
      { id: "Cologne", label: "Cologne" },
      { id: "Oil Perfumes", label: "Oil Perfumes" },
      { id: "Niche Perfume", label: "Niche Perfume" },
      { id: "Elite Perfume", label: "Elite Perfume" },
      { id: "Arabic Perfume", label: "Arabic Perfume" },
      { id: "Atomizers", label: "Atomizers" },
      { id: "Home Fragrances", label: "Home Fragrances" },
    ],
  },
  {
    id: "Makeup",
    label: "Makeup",
    children: [
      { id: "Eyes", label: "Eyes" },
      { id: "Eyebrows", label: "Eyebrows" },
      { id: "Lips", label: "Lips" },
      { id: "Face", label: "Face" },
      { id: "Brushes", label: "Brushes" },
      { id: "Makeup Remover", label: "Makeup Remover" },
      { id: "Nails", label: "Nails" },
      { id: "Makeup Palette", label: "Makeup Palette" },
      { id: "Miniatures", label: "Miniatures" },
      { id: "Palette", label: "Palette" },
    ],
  },

  {
    id: "Body",
    label: "Body",
    children: [
      { id: "Bath and shower", label: "Bath and shower" },
      { id: "Hygiene", label: "Hygiene" },
      { id: "Oral care", label: "Oral care" },
      { id: "Depilation", label: "Depilation" },
      { id: "Deodorants", label: "Deodorants" },
      { id: "Body cosmetics", label: "Body cosmetics" },
      { id: "Hand cosmetics", label: "Hand cosmetics" },
      { id: "Foot cosmetics", label: "Foot cosmetics" },
      { id: "Massage products", label: "Massage products" },
      { id: "Anti-cellulite", label: "Anti-cellulite" },
      { id: "Suntan products", label: "Suntan products" },
      { id: "Sun protection", label: "Sun protection" },
      { id: "Oils", label: "Oils" },
      { id: "Home fragrances", label: "Home fragrances" },
    ],
  },
];

export const goods = [
  {
    id: 1,
    name: "products.shampoo.name",
    description: "products.shampoo.description",
    category: "Hair",
    subCategory: "Shampoos",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/shampoo.webp",
  },
  {
    id: 2,
    name: "products.conditioner.name",
    description: "products.conditioner.description",
    category: "Hair",
    subCategory: "Conditioners",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 3,
    name: "products.hairMask.name",
    description: "products.hairMask.description",
    category: "Hair",
    subCategory: "Hair masks",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/masque.jpg",
  },
  {
    id: 4,
    name: "products.hairRinse.name",
    description: "products.hairRinse.description",
    category: "Hair",
    subCategory: "Hair rinse",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/rinse.jpg",
  },
  {
    id: 5,
    name: "products.hairLotion.name",
    description: "products.hairLotion.description",
    category: "Hair",
    subCategory: "Hair lotion",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/lotion.jpg",
  },
  {
    id: 6,
    name: "products.hairOil.name",
    description: "products.hairOil.description",
    category: "Hair",
    subCategory: "Hair oil",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/oil.jpg",
  },
  {
    id: 7,
    name: "products.hairSerum.name",
    description: "products.hairSerum.description",
    category: "Hair",
    subCategory: "Hair serum",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/serum.jpg",
  },
  {
    id: 8,
    name: "products.hairCream.name",
    description: "products.hairCream.description",
    category: "Hair",
    subCategory: "Hair cream",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 9,
    name: "products.hairSpray.name",
    description: "products.hairSpray.description",
    category: "Hair",
    subCategory: "Hair spray",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/spray.jpg",
  },
  {
    id: 10,
    name: "products.hairKeratin.name",
    description: "products.hairKeratin.description",
    category: "Hair",
    subCategory: "Hair keratin",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/keratin.jpg",
  },
  {
    id: 11,
    name: "products.shampoo.name",
    description: "products.shampoo.description",
    category: "Hair",
    subCategory: "Shampoos",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/shampoo.webp",
  },
  {
    id: 12,
    name: "products.conditioner.name",
    description: "products.conditioner.description",
    category: "Hair",
    subCategory: "Conditioners",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 13,
    name: "products.hairMask.name",
    description: "products.hairMask.description",
    category: "Hair",
    subCategory: "Hair masks",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/masque.jpg",
  },
  {
    id: 14,
    name: "products.hairRinse.name",
    description: "products.hairRinse.description",
    category: "Hair",
    subCategory: "Hair rinse",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/rinse.jpg",
  },
  {
    id: 15,
    name: "products.hairLotion.name",
    description: "products.hairLotion.description",
    category: "Hair",
    subCategory: "Hair lotion",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/lotion.jpg",
  },
  {
    id: 16,
    name: "products.hairOil.name",
    description: "products.hairOil.description",
    category: "Hair",
    subCategory: "Hair oil",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/oil.jpg",
  },
  {
    id: 17,
    name: "products.hairSerum.name",
    description: "products.hairSerum.description",
    category: "Hair",
    subCategory: "Hair serum",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/serum.jpg",
  },
  {
    id: 18,
    name: "products.hairCream.name",
    description: "products.hairCream.description",
    category: "Hair",
    subCategory: "Hair cream",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 19,
    name: "products.hairSpray.name",
    description: "products.hairSpray.description",
    category: "Hair",
    subCategory: "Hair spray",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/spray.jpg",
  },
  {
    id: 20,
    name: "products.hairKeratin.name",
    description: "products.hairKeratin.description",
    category: "Hair",
    subCategory: "Hair keratin",
    raiting: 4.5,
    volume: 200,
    price: 100,
    imsrcOfImg: "/goods/keratin.jpg",
  },
];
export const promoItems = [
  {
    id: 1,
    name: "products.shampoo.name",
    description: "products.shampoo.description",
    category: "Hair",
    subCategory: "Shampoos",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/shampoo.webp",
  },
  {
    id: 2,
    name: "products.conditioner.name",
    description: "products.conditioner.description",
    category: "Hair",
    subCategory: "Conditioners",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 3,
    name: "products.hairMask.name",
    description: "products.hairMask.description",
    category: "Hair",
    subCategory: "Hair masks",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/masque.jpg",
  },
  {
    id: 4,
    name: "products.hairRinse.name",
    description: "products.hairRinse.description",
    category: "Hair",
    subCategory: "Hair rinse",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/rinse.jpg",
  },
  {
    id: 5,
    name: "products.hairLotion.name",
    description: "products.hairLotion.description",
    category: "Hair",
    subCategory: "Hair lotion",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 25,
    discountPrice: 75,
    imsrcOfImg: "/goods/lotion.jpg",
  },
  {
    id: 6,
    name: "products.hairOil.name",
    description: "products.hairOil.description",
    category: "Hair",
    subCategory: "Hair oil",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/oil.jpg",
  },
  {
    id: 7,
    name: "products.hairSerum.name",
    description: "products.hairSerum.description",
    category: "Hair",
    subCategory: "Hair serum",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/serum.jpg",
  },
  {
    id: 8,
    name: "products.hairCream.name",
    description: "products.hairCream.description",
    category: "Hair",
    subCategory: "Hair cream",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 9,
    name: "products.hairSpray.name",
    description: "products.hairSpray.description",
    category: "Hair",
    subCategory: "Hair spray",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/spray.jpg",
  },
  {
    id: 10,
    name: "products.hairKeratin.name",
    description: "products.hairKeratin.description",
    category: "Hair",
    subCategory: "Hair keratin",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/keratin.jpg",
  },
  {
    id: 11,
    name: "products.shampoo.name",
    description: "products.shampoo.description",
    category: "Hair",
    subCategory: "Shampoos",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/shampoo.webp",
  },
  {
    id: 12,
    name: "products.conditioner.name",
    description: "products.conditioner.description",
    category: "Hair",
    subCategory: "Conditioners",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 13,
    name: "products.hairMask.name",
    description: "products.hairMask.description",
    category: "Hair",
    subCategory: "Hair masks",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/masque.jpg",
  },
  {
    id: 14,
    name: "products.hairRinse.name",
    description: "products.hairRinse.description",
    category: "Hair",
    subCategory: "Hair rinse",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/rinse.jpg",
  },
  {
    id: 15,
    name: "products.hairLotion.name",
    description: "products.hairLotion.description",
    category: "Hair",
    subCategory: "Hair lotion",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 25,
    discountPrice: 75,
    imsrcOfImg: "/goods/lotion.jpg",
  },
  {
    id: 16,
    name: "products.hairOil.name",
    description: "products.hairOil.description",
    category: "Hair",
    subCategory: "Hair oil",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/oil.jpg",
  },
  {
    id: 17,
    name: "products.hairSerum.name",
    description: "products.hairSerum.description",
    category: "Hair",
    subCategory: "Hair serum",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/serum.jpg",
  },
  {
    id: 18,
    name: "products.hairCream.name",
    description: "products.hairCream.description",
    category: "Hair",
    subCategory: "Hair cream",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 19,
    name: "products.hairSpray.name",
    description: "products.hairSpray.description",
    category: "Hair",
    subCategory: "Hair spray",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/spray.jpg",
  },
  {
    id: 20,
    name: "products.hairKeratin.name",
    description: "products.hairKeratin.description",
    category: "Hair",
    subCategory: "Hair keratin",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/keratin.jpg",
  },
  {
    id: 21,
    name: "products.shampoo.name",
    description: "products.shampoo.description",
    category: "Hair",
    subCategory: "Shampoos",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/shampoo.webp",
  },
  {
    id: 22,
    name: "products.conditioner.name",
    description: "products.conditioner.description",
    category: "Hair",
    subCategory: "Conditioners",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 23,
    name: "products.hairMask.name",
    description: "products.hairMask.description",
    category: "Hair",
    subCategory: "Hair masks",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/masque.jpg",
  },
  {
    id: 24,
    name: "products.hairRinse.name",
    description: "products.hairRinse.description",
    category: "Hair",
    subCategory: "Hair rinse",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/rinse.jpg",
  },
  {
    id: 25,
    name: "products.hairLotion.name",
    description: "products.hairLotion.description",
    category: "Hair",
    subCategory: "Hair lotion",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 25,
    discountPrice: 75,
    imsrcOfImg: "/goods/lotion.jpg",
  },
  {
    id: 26,
    name: "products.hairOil.name",
    description: "products.hairOil.description",
    category: "Hair",
    subCategory: "Hair oil",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/oil.jpg",
  },
  {
    id: 27,
    name: "products.hairSerum.name",
    description: "products.hairSerum.description",
    category: "Hair",
    subCategory: "Hair serum",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/serum.jpg",
  },
  {
    id: 28,
    name: "products.hairCream.name",
    description: "products.hairCream.description",
    category: "Hair",
    subCategory: "Hair cream",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 10,
    discountPrice: 90,
    imsrcOfImg: "/goods/vitamin.webp",
  },
  {
    id: 29,
    name: "products.hairSpray.name",
    description: "products.hairSpray.description",
    category: "Hair",
    subCategory: "Hair spray",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 15,
    discountPrice: 85,
    imsrcOfImg: "/goods/spray.jpg",
  },
  {
    id: 30,
    name: "products.hairKeratin.name",
    description: "products.hairKeratin.description",
    category: "Hair",
    subCategory: "Hair keratin",
    raiting: 4.5,
    volume: 200,
    price: 100,
    discount: 20,
    discountPrice: 80,
    imsrcOfImg: "/goods/keratin.jpg",
  },
];
